FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o main .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
# Add curl for healthcheck
RUN apk add --no-cache curl
EXPOSE 8001
HEALTHCHECK --interval=30s --timeout=3s \
CMD curl -f http://localhost:8001/ping || exit 1
CMD ["./main"]