version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - service1
      - service2
    networks:
      - my_network

  service1:
    build: ./service_1
    expose:
      - "8001"
    networks:
      - my_network

  service2:
    build: ./service_2
    expose:
      - "8002"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge