FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY pyproject.toml .
COPY app.py .

RUN pip install uv && \
    uv pip install --system flask==3.1.1

EXPOSE 8002
HEALTHCHECK --interval=30s --timeout=3s \
CMD curl -f http://localhost:8002/ping || exit 1

CMD ["python", "app.py"]